name: gesture_detector_with_preview
description: A simple gesture detector widget with preview.
version: 1.0.0
homepage: https://github.com/edjostenes/gesture_detector_with_preview

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: